### ISSUE TITLE
Write about the flowcharts

### ISSUE THREAD

**Issue by Laursen79** [P1-A408b-AAU2020/plusbussim#13]
https://app.diagrams.net/?src=about#Wb!0U-CNYvl3E-frXvt1d1Tl8DQLpmfImlCtUMR9Ng_-OYLA0orcHueTaMKJoAaEoM6%2F01CRK76C7AFIVVLHXSAFDY45UWB7L3FBQV

**Comment by MJHC** [comment]
We have written what was possible, now we need to wait for lane changes to be finished
