### ISSUE TITLE
Make a node management system

### ISSUE THREAD

**Issue by Skovrup1** [P1-A408b-AAU2020/plusbussim#20]
Som skal holde styr på hvilke edges (veje) er forbundne med hvilke nodes (intersections)
https://www.khanacademy.org/computing/computer-science/algorithms/graph-representation/a/representing-graphs

**Comment by Laursen79** [comment]
Har vi brug for det her, når vi ikke skal finde vej?

**Comment by Skovrup1** [comment]
Vi skal vel vide hvilke veje er forbundet men havde du ikke allerede lavet en måde man kunne tjekke det på?
