### ISSUE TITLE
How will pocket lanes work?

### ISSUE THREAD

**Issue by Laursen79** [P1-A408b-AAU2020/plusbussim#24]

**Comment by MJHC** [comment]
Made a flow chart on how pocket lanes work.

**Comment by MJHC** [comment]
![image](https://user-images.githubusercontent.com/26723180/100091742-50f0fa80-2e55-11eb-9149-57ca5fda5a18.png)

**Comment by AlexanderSteffensen** [comment]
Maps over different pocket lanes are in paper and will be scanned into the P1 folder on Onedrive
