### ISSUE TITLE
Green light manangement

### ISSUE THREAD

**Issue by KiraStaehr** [P1-A408b-AAU2020/plusbussim#25]

**Comment by KiraStaehr** [comment]
Flowchart over et forslag til hvordan trafiklys kan fungerehvor inputtet er en nodeid
<img width="592" alt="Trafficlight_flowchart" src="https://user-images.githubusercontent.com/74182118/100090230-2605a700-2e53-11eb-8388-e62db0f91dbf.PNG">

**Comment by AlexanderSteffensen** [comment]
The traffic lights has been implemented and therefore this part is done
