### ISSUE TITLE
Implement all the different types of intersections on the route

### ISSUE THREAD

**Issue by Laursen79** [P1-A408b-AAU2020/plusbussim#27]
![image](https://user-images.githubusercontent.com/69715502/100440114-aa9b3400-30a4-11eb-9175-2777da995cac.png)

**Comment by AlexanderSteffensen** [comment]
#Status so far, these intersections has been implemented ![Uploading 100734379...]

**Comment by AlexanderSteffensen** [comment]
![image](https://user-images.githubusercontent.com/74182126/100734420-f2d19380-33cf-11eb-90cb-a31fbb2fb0fc.jpeg)

**Comment by AlexanderSteffensen** [comment]
Update, 10th intersection is not existing on the route ![image](https://user-images.githubusercontent.com/74182126/100872276-db62db00-34a1-11eb-99ef-f665e8dcd635.jpeg)

**Comment by AlexanderSteffensen** [comment]
Im starting to implement intersection 1
