### ISSUE TITLE
Instantiate (place new vehicles) on roads.

### ISSUE THREAD

**Issue by Laursen79** [P1-A408b-AAU2020/plusbussim#7]
If a road is not connected to anything, vehicles should be instantiated on that road based on a chance.

Car should instantiate where the arrows point to.
![image](https://user-images.githubusercontent.com/69715502/99534032-11369880-29a7-11eb-843e-48c86204b02c.png)

**Comment by MJHC** [comment]
Have made some suggestions: will be presented 25/11

**Comment by MJHC** [comment]
Lasr for loop in  init_actors  should be made in to a function called place_actor, so it can be used more places. 
Some of the parameters the function should have is:
- Actors(Struct)
- Links (Random link)
The function should be able to move cars from one link to a random link.

**Comment by AlexanderSteffensen** [comment]
This function has been implemented in the simulation and works
